SELECT ?y
FROM <window>
WHERE {
   <-231163918>  <http://yago-knowledge.org/resource/isLocatedIn> / <http://yago-knowledge.org/resource/dealsWith> / <http://yago-knowledge.org/resource/hasCapital> ?y .
}