// Automatically generated by the DDlog compiler.
package ddlog.tc;
import com.google.flatbuffers.*;
public final class EdgeReader
{
    protected EdgeReader(ddlog.__tc.Edge inner) { this.inner = inner; }
    private ddlog.__tc.Edge inner;
    public long s ()
    {
        return (long)this.inner.s();
    }
    public long t ()
    {
        return (long)this.inner.t();
    }
}