// Automatically generated by the DDlog compiler.
package ddlog.tc;
import com.google.flatbuffers.*;
public final class PathReader
{
    protected PathReader(ddlog.__tc.Path inner) { this.inner = inner; }
    private ddlog.__tc.Path inner;
    public long s1 ()
    {
        return (long)this.inner.s1();
    }
    public long s2 ()
    {
        return (long)this.inner.s2();
    }
}