// Automatically generated by the DDlog compiler.
package ddlog.tc;
import ddlogapi.DDlogAPI;
import ddlogapi.DDlogException;
import com.google.flatbuffers.*;
public class tcFlatBufferBuilder
{
    protected FlatBufferBuilder fbbuilder;
    public tcFlatBufferBuilder() {
        fbbuilder = new FlatBufferBuilder();
    }
    public tcFlatBufferBuilder(FlatBufferBuilder fbbuilder) {
        this.fbbuilder = fbbuilder;
    }
    public EdgeWriter create_Edge(long s, long t)
    {
        return new EdgeWriter(ddlog.__tc.Edge.createEdge(fbbuilder, s, t));
    }
    public PathWriter create_Path(long s1, long s2)
    {
        return new PathWriter(ddlog.__tc.Path.createPath(fbbuilder, s1, s2));
    }
    public Tuple0Writer create_Tuple0()
    {
        return new Tuple0Writer(((java.util.function.Supplier<Integer>) (() -> 
                                {
                                    ddlog.__tc.Tuple0.startTuple0(fbbuilder);
                                    return Integer.valueOf( ddlog.__tc.Tuple0.endTuple0(fbbuilder));
                                })).get());
    }
}