// Automatically generated by the DDlog compiler.
package ddlog.tc;
import com.google.flatbuffers.*;
public final class Tuple0Reader
{
    protected Tuple0Reader(ddlog.__tc.Tuple0 inner) { this.inner = inner; }
    private ddlog.__tc.Tuple0 inner;
}