// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__tc;

public final class __CommandKind {
  private __CommandKind() { }
  public static final byte Insert = 0;
  public static final byte Delete = 1;

  public static final String[] names = { "Insert", "Delete", };

  public static String name(int e) { return names[e]; }
}

