// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__tc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class __Commands extends Table {
  public static __Commands getRootAs__Commands(ByteBuffer _bb) { return getRootAs__Commands(_bb, new __Commands()); }
  public static __Commands getRootAs__Commands(ByteBuffer _bb, __Commands obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public __Commands __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public __Command commands(int j) { return commands(new __Command(), j); }
  public __Command commands(__Command obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int commandsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int create__Commands(FlatBufferBuilder builder,
      int commandsOffset) {
    builder.startObject(1);
    __Commands.addCommands(builder, commandsOffset);
    return __Commands.end__Commands(builder);
  }

  public static void start__Commands(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addCommands(FlatBufferBuilder builder, int commandsOffset) { builder.addOffset(0, commandsOffset, 0); }
  public static int createCommandsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCommandsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int end__Commands(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finish__CommandsBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixed__CommandsBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

