// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__tc;

public final class __Value {
  private __Value() { }
  public static final byte NONE = 0;
  public static final byte Edge = 1;
  public static final byte Path = 2;
  public static final byte Tuple0 = 3;

  public static final String[] names = { "NONE", "Edge", "Path", "Tuple0", };

  public static String name(int e) { return names[e]; }
}

