// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__tc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Tuple0 extends Table {
  public static Tuple0 getRootAsTuple0(ByteBuffer _bb) { return getRootAsTuple0(_bb, new Tuple0()); }
  public static Tuple0 getRootAsTuple0(ByteBuffer _bb, Tuple0 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public Tuple0 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startTuple0(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endTuple0(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

